apiVersion: apps/v1
kind: Deployment
metadata:
  name: tata-devop-prod
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tata-devop
  template:
    metadata:
      labels:
        app: tata-devop
    spec:
      containers:
        - name: tata-devop-prod
          image: 533267371412.dkr.ecr.us-west-2.amazonaws.com/tata-devop-prod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tata-devop-secrets-prod
                  key: JWT_SECRET_KEY
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: tata-devop-secrets-prod
                  key: JWT_EXPIRATION
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: tata-devop-secrets-prod
                  key: API_KEY
            - name: APP_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: tata-devop-secrets-prod
                  key: APP_ENVIRONMENT

---
apiVersion: v1
kind: Service
metadata:
  name: tata-devop-prod-service
  namespace: prod
spec:
  selector:
    app: tata-devop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
